/**
 * Build markdown string from strategy agent result JSON for onboarding Step 1 report.
 */

export interface StrategyResultInputProduct {
  name?: string
  category?: string
  core_value_prop?: string
  job_it_replaces?: string
  target_customer?: string
}

export interface StrategyResultCompetitor {
  name?: string
  what_they_do?: string
  complaints?: string[]
  quotes?: string[]
}

export interface StrategyResultStatusQuo {
  description?: string
  frustrations?: string[]
}

export interface StrategyResultTrend {
  trend?: string
  momentum?: string
  time_horizon?: string
  evidence?: string
}

export interface StrategyResultThreat {
  threat?: string
  who_is_driving_it?: string
  how_fast_moving?: string
  urgency?: string
  recommended_response?: string
}

export interface StrategyResultUnmetNeed {
  need?: string
  how_widespread?: string
  evidence?: string
  trend_connection?: string
  framework_angle?: string
}

export interface StrategyResultMomentumAdvantage {
  advantage?: string
  trend_backing?: string
  recommendation?: string
}

export interface StrategyResultRankedOpportunity {
  rank?: number
  opportunity?: string
  composite_score?: number
  segment_size_score?: number
  segment_size_reasoning?: string
  pain_urgency_score?: number
  pain_urgency_reasoning?: string
  strategic_fit_score?: number
  strategic_fit_reasoning?: string
  target_segment?: string
  recommended_action?: string
  pm_comment?: string
}

export interface StrategyResultData {
  input_product?: StrategyResultInputProduct
  stage?: string
  framework_applied?: string
  framework_selection_reasoning?: string
  icp_inferred_from_competitors?: boolean
  icp_inference_reasoning?: string
  direct_competitors?: StrategyResultCompetitor[]
  indirect_competitors?: StrategyResultCompetitor[]
  status_quo?: StrategyResultStatusQuo
  emerging_trends?: StrategyResultTrend[]
  new_threats?: StrategyResultThreat[]
  unmet_needs?: StrategyResultUnmetNeed[]
  momentum_advantages?: StrategyResultMomentumAdvantage[]
  ranked_opportunities?: StrategyResultRankedOpportunity[]
  recommended_wedge?: string
  threats_to_monitor?: StrategyResultThreat[]
}

function esc(s: string | undefined): string {
  return (s ?? '').replace(/\|/g, '\\|')
}

function block(s: string | undefined): string {
  return (s ?? '').trim() ? `${(s ?? '').trim()}\n\n` : ''
}

export function buildReportMarkdown(data: StrategyResultData): string {
  const d = data
  const p = d.input_product ?? {}
  const date = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })

  let md = `# Product Strategy Report\n*Generated by NorthStar · ${date}*\n\n`
  md += `## Product Overview\n`
  md += `**Name:** ${p.name ?? '—'}\n`
  md += `**Category:** ${p.category ?? '—'}\n`
  md += `**Stage:** ${d.stage ?? '—'}\n`
  md += `**Framework Applied:** ${d.framework_applied ?? '—'}\n\n`
  if (d.framework_selection_reasoning) {
    md += `> ${d.framework_selection_reasoning}\n\n`
  }
  md += `**Core Value Prop:** ${p.core_value_prop ?? '—'}\n`
  md += `**Job it Replaces:** ${p.job_it_replaces ?? '—'}\n\n---\n\n`
  md += `## Target Customer\n${block(p.target_customer)}`
  if (d.icp_inferred_from_competitors && d.icp_inference_reasoning) {
    md += `*ICP inferred from competitor research: ${d.icp_inference_reasoning}*\n\n`
  }
  md += `---\n\n## Competitive Landscape\n\n### Direct Competitors\n\n`
  for (const c of d.direct_competitors ?? []) {
    md += `**${c.name ?? '—'}**\n${block(c.what_they_do)}`
    if (c.complaints?.length) {
      md += `Top complaints:\n${c.complaints.map((x) => `- ${x}`).join('\n')}\n\n`
    }
    if (c.quotes?.length) {
      md += c.quotes.map((q) => `> "${q}"`).join('\n') + '\n\n'
    }
  }
  md += `### Indirect Competitors\n\n`
  for (const c of d.indirect_competitors ?? []) {
    md += `**${c.name ?? '—'}**\n${block(c.what_they_do)}`
    if (c.complaints?.length) {
      md += `Top complaints:\n${c.complaints.map((x) => `- ${x}`).join('\n')}\n\n`
    }
    if (c.quotes?.length) {
      md += c.quotes.map((q) => `> "${q}"`).join('\n') + '\n\n'
    }
  }
  const sq = d.status_quo
  if (sq) {
    md += `### Status Quo\n${block(sq.description)}`
    if (sq.frustrations?.length) {
      md += `Frustrations:\n${sq.frustrations.map((x) => `- ${x}`).join('\n')}\n\n`
    }
  }
  md += `---\n\n## Market Trends\n\n`
  for (const t of d.emerging_trends ?? []) {
    md += `**${t.trend ?? '—'}** · ${t.momentum ?? ''} · ${t.time_horizon ?? ''}\n${block(t.evidence)}`
  }
  md += `### New Threats\n`
  for (const t of d.new_threats ?? []) {
    md += `- **${t.threat ?? '—'}** — driven by ${t.who_is_driving_it ?? '—'} [${t.how_fast_moving ?? ''} urgency]\n`
  }
  md += `\n---\n\n## Unmet Needs\n\n`
  for (const u of d.unmet_needs ?? []) {
    md += `### ${u.need ?? '—'} · ${u.how_widespread ?? ''} priority\n${block(u.evidence)}`
    if (u.trend_connection) md += `*Why now:* ${u.trend_connection}\n`
    if (u.framework_angle) md += `*Strategic angle:* ${u.framework_angle}\n`
    md += '\n'
  }
  md += `---\n\n## Momentum Advantages\n\n`
  for (const m of d.momentum_advantages ?? []) {
    md += `**${m.advantage ?? '—'}**\nTrend backing: ${m.trend_backing ?? '—'}\nRecommendation: ${m.recommendation ?? '—'}\n\n`
  }
  md += `---\n\n## Ranked Opportunities\n\n`
  const sorted = [...(d.ranked_opportunities ?? [])].sort((a, b) => (a.rank ?? 0) - (b.rank ?? 0))
  for (const r of sorted) {
    md += `### #${r.rank ?? '?'} — ${r.opportunity ?? '—'}\n`
    md += `**Composite Score: ${r.composite_score ?? '—'}/10**\n\n`
    md += `| Dimension | Score | Reasoning |\n|---|---|---|\n`
    md += `| Segment size | ${r.segment_size_score ?? '—'}/10 | ${esc(r.segment_size_reasoning)} |\n`
    md += `| Pain urgency | ${r.pain_urgency_score ?? '—'}/10 | ${esc(r.pain_urgency_reasoning)} |\n`
    md += `| Strategic fit | ${r.strategic_fit_score ?? '—'}/10 | ${esc(r.strategic_fit_reasoning)} |\n\n`
    md += `**Target segment:** ${r.target_segment ?? '—'}\n`
    md += `**Recommended action:** ${r.recommended_action ?? '—'}\n`
    if (r.pm_comment) md += `**PM note:** ${r.pm_comment}\n`
    md += '\n'
  }
  md += `---\n\n## Recommended Wedge\n\n${block(d.recommended_wedge)}---\n\n## Threats to Monitor\n\n`
  for (const t of d.threats_to_monitor ?? []) {
    md += `**${t.threat ?? '—'}** [${t.urgency ?? ''}]\nDriven by: ${t.who_is_driving_it ?? '—'}\nResponse: ${t.recommended_response ?? '—'}\n\n`
  }
  md += `---\n*Strategy generated by NorthStar Market Intelligence Agent*\n`
  return md
}
