export const PERSONAS = [
  {
    id: 'skeptical-senior-eng',
    role: 'Senior Engineer',
    company_stage: 'Series B',
    device: 'desktop',
    attention_span: '8 seconds',
    primary_fear: 'another AI tool that overpromises',
    primary_desire: 'see real code and real proof',
    first_question: 'what access does this need to my repo?',
    converts_if: 'sees concrete technical proof and safety controls',
  },
  {
    id: 'curious-mid-eng',
    role: 'Mid-level Engineer',
    company_stage: 'Series A',
    device: 'mobile',
    attention_span: '15 seconds',
    primary_fear: 'wasting time on a tool that doesnt work',
    primary_desire: 'quick proof it actually ships code',
    first_question: 'how does it actually work?',
    converts_if: 'sees a demo or example PR within 10 seconds',
  },
  {
    id: 'burnout-eng-lead',
    role: 'Engineering Lead',
    company_stage: 'Series B',
    device: 'desktop',
    attention_span: '25 seconds',
    primary_fear: 'agent breaks production',
    primary_desire: 'ship features without more meetings',
    first_question: 'is it safe to run on production?',
    converts_if: 'sees canary deployment and human approval flow',
  },
  {
    id: 'security-eng',
    role: 'Security Engineer',
    company_stage: 'Series B',
    device: 'desktop',
    attention_span: '5 seconds',
    primary_fear: 'giving unknown tool access to private repo',
    primary_desire: 'understand exact permission scope',
    first_question: 'what GitHub permissions does this request?',
    converts_if: 'sees explicit minimal permission list upfront',
  },
  {
    id: 'opensource-eng',
    role: 'Open Source Engineer',
    company_stage: 'Startup',
    device: 'desktop',
    attention_span: '20 seconds',
    primary_fear: 'black box AI touching my code',
    primary_desire: 'understand exactly what the agent does',
    first_question: 'is this open source or explainable?',
    converts_if: 'sees transparent hypothesis reasoning',
  },
  {
    id: 'growth-pm',
    role: 'Growth PM',
    company_stage: 'Series A',
    device: 'mobile',
    attention_span: '20 seconds',
    primary_fear: 'tool doesnt move real metrics',
    primary_desire: 'see conversion lift numbers',
    first_question: 'what is the average conversion improvement?',
    converts_if: 'sees concrete metric improvement evidence',
  },
  {
    id: 'senior-pm',
    role: 'Senior PM',
    company_stage: 'Series B',
    device: 'desktop',
    attention_span: '30 seconds',
    primary_fear: 'another tool to manage',
    primary_desire: 'autonomous improvement with no overhead',
    first_question: 'how much time does this actually save?',
    converts_if: 'understands it runs without PM involvement',
  },
  {
    id: 'technical-pm',
    role: 'Technical PM ex-engineer',
    company_stage: 'Series B',
    device: 'desktop',
    attention_span: '45 seconds',
    primary_fear: 'agent makes bad product decisions',
    primary_desire: 'understand the hypothesis quality',
    first_question: 'how does it form hypotheses?',
    converts_if: 'sees the signal-to-hypothesis reasoning explained',
  },
  {
    id: 'skeptical-cpo',
    role: 'CPO',
    company_stage: 'Series B',
    device: 'mobile',
    attention_span: '10 seconds',
    primary_fear: 'expensive tool with no clear ROI',
    primary_desire: 'revenue impact in dollars',
    first_question: 'what is the ROI?',
    converts_if: 'sees dollar impact calculation immediately',
  },
] as const

export type PersonaId = typeof PERSONAS[number]['id']
