import { NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import { DEMO_INSIGHTS, DEMO_PRD_CONTENT } from '@/lib/demo-data'

export async function POST(request: Request) {
  try {
    const { insightId, demo } = await request.json()

    // Find insight (demo or DB)
    let insight
    if (demo || insightId?.startsWith('demo-')) {
      const index = parseInt(insightId?.replace('demo-insight-', '') || '1')
      const demoInsight = DEMO_INSIGHTS[index] || DEMO_INSIGHTS[1]
      insight = { ...demoInsight, id: insightId }
    } else {
      // Fetch from Supabase
      const { createClient } = await import('@/lib/supabase/server')
      const supabase = createClient()
      const { data, error } = await supabase
        .from('insights')
        .select('*')
        .eq('id', insightId)
        .single()

      if (error || !data) {
        return NextResponse.json({ error: 'Insight not found' }, { status: 404 })
      }
      insight = data
    }

    // Check for Anthropic API key
    const apiKey = process.env.ANTHROPIC_API_KEY
    if (!apiKey) {
      // Return demo PRD if no API key
      const prd = {
        id: `prd-${Date.now()}`,
        org_id: insight.org_id,
        insight_id: insightId,
        title: `PRD: ${insight.title}`,
        content: DEMO_PRD_CONTENT,
        status: 'draft',
        created_by: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      }
      return NextResponse.json({ prd })
    }

    // Generate with Claude
    const anthropic = new Anthropic({ apiKey })

    const evidenceText = insight.evidence?.map((e: { quote: string; customer?: string; source_type: string; date: string }) =>
      `- "${e.quote}" — ${e.customer || 'Customer'} via ${e.source_type} (${new Date(e.date).toLocaleDateString()})`
    ).join('\n') || 'No evidence available'

    const prompt = `You are NorthStar, an expert AI Product Manager. Generate a comprehensive, well-structured PRD for the following product opportunity.

**Problem/Opportunity**: ${insight.title}
**Summary**: ${insight.summary}
**Severity**: ${insight.severity}
**Mentions**: ${insight.mention_count} customer mentions
**Revenue Impact**: ${insight.revenue_impact || 'Not specified'}

**Customer Evidence**:
${evidenceText}

Generate a full PRD in Markdown with these sections:
1. Executive Summary (2-3 sentences, lead with business impact)
2. Problem Statement (include 2-3 customer quotes from the evidence above)
3. User Personas (who is affected, their goals and pain points)
4. Success Metrics (table with metric, target, timeline)
5. User Stories (Must Have, Should Have, Could Have - each with acceptance criteria)
6. Technical Considerations (key technical decisions and constraints)
7. Risks & Mitigations (table with risk, likelihood, impact, mitigation)

Requirements:
- Be specific and actionable, not vague
- Include all customer quotes from the evidence
- Make success metrics measurable with specific targets
- Write acceptance criteria as checkboxes
- Note at the bottom: "Generated by NorthStar on [date] based on [N] customer conversations"

Format in clean Markdown.`

    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-5-20250929',
      max_tokens: 6000,
      messages: [{ role: 'user', content: prompt }],
    })

    const content = message.content[0].type === 'text' ? message.content[0].text : DEMO_PRD_CONTENT

    const prd = {
      id: `prd-${Date.now()}`,
      org_id: insight.org_id,
      insight_id: insightId,
      title: `PRD: ${insight.title}`,
      content,
      status: 'draft',
      created_by: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }

    // Save to DB if not demo
    if (!demo && !insightId?.startsWith('demo-')) {
      const { createClient } = await import('@/lib/supabase/server')
      const supabase = createClient()
      await supabase.from('prds').insert({
        ...prd,
        org_id: insight.org_id,
      })
    }

    return NextResponse.json({ prd })
  } catch (error) {
    console.error('PRD generation error:', error)
    // Return demo PRD as fallback
    const prd = {
      id: `prd-${Date.now()}`,
      org_id: 'demo-org',
      insight_id: null,
      title: 'PRD: Single Sign-On (SSO) Integration',
      content: DEMO_PRD_CONTENT,
      status: 'draft',
      created_by: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }
    return NextResponse.json({ prd })
  }
}
