-- Migration 010: agent_hypotheses table
-- Stores structured improvement hypotheses generated by the analysis pipeline.

CREATE TABLE IF NOT EXISTS public.agent_hypotheses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id UUID NOT NULL REFERENCES public.agents(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  source TEXT NOT NULL,
  hypothesis TEXT NOT NULL,
  suggested_change TEXT,
  impact_score INTEGER DEFAULT 3 CHECK (impact_score BETWEEN 1 AND 5),
  status TEXT NOT NULL DEFAULT 'proposed'
    CHECK (status IN ('proposed', 'accepted', 'rejected', 'shipped')),
  pr_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.agent_hypotheses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own agent hypotheses" ON public.agent_hypotheses
  USING (agent_id IN (SELECT id FROM public.agents WHERE user_id = auth.uid()));
